[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/social/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://x.com"
