[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"


[[redirects]]
  from = "/giveaway"
  to = "/?giveaway=1"
  status = 302

[[redirects]]
  from = "/giveaway-rules"
  to = "/giveaway-rules.html"
  status = 200
